### ISSUE TITLE
Allow HTTP proxy to be specified

### ISSUE THREAD

**Issue by macbre** [macbre/analyze-css#120]
Use [node-fetch](https://www.npmjs.com/package/node-fetch), a lightweight HTTP client for Node.js.

This will help us with https://github.com/macbre/phantomas/issues/500

* https://nodejs.org/api/http.html#http_class_http_agent
* http://stackoverflow.com/a/6781592
* use `HTTP_PROXY` env variable if defined

@gmetais

**Comment by gmetais** [comment]
👍
