### ISSUE TITLE
Running command line just prints usage instructions

### ISSUE THREAD

**Issue by Dottenpixel** [macbre/analyze-css#268]
![Image 2021-03-15 at 2 18 08 PM](https://user-images.githubusercontent.com/227507/111223209-12b14f80-859a-11eb-8fc5-565df3160243.jpg)

**Comment by macbre** [comment]
@Dottenpixel - this is now fixed in the main branch. Will publish an updated version to npm soon.

Thanks for reporting this 🤦🏻 bug 🙂

**Comment by macbre** [comment]
https://www.npmjs.com/package/analyze-css - v0.13.0 is out there.

**Comment by Dottenpixel** [comment]
Excellent! Thanks @macbre!
