### ISSUE TITLE
New metric: average selectors length

### ISSUE THREAD

**Issue by gmetais** [macbre/analyze-css#62]
Hi @macbre!

What about having a metric giving the average length of selectors?

For example:
```css
div .foo {}
div .bar {}
div .foo .bar {}
```
has an average complexity of 2.333

By the way, is there a reason why analyze-css doesn't count attribute expressions in the complexity?
For example `.form_b2_legacy .row-fluid input[class*="span"]` has 4 expressions but is not in the complexSelectors offenders.

Gaël

**Comment by macbre** [comment]
Let's implement "average selectors length" metric and move the complexity score discussion to a different issue :)

**Comment by gmetais** [comment]
Good for me!
