### ISSUE TITLE
Falsely redundant "body > .foo .bar"

### ISSUE THREAD

**Issue by Minopolis** [macbre/analyze-css#82]
Hey there,
I noticed that selectors like "body > .foo .bar" return to be a redundantBodySelector, even though the body selector is combined with a child selector.
Is this wanted behaviour?
Thanks, Matt

**Comment by macbre** [comment]
No, definitely a bug.

**Comment by gmetais** [comment]
You were right @Minopolis :)

**Comment by macbre** [comment]
Thanks for reporting, @Minopolis.

Published to npm as v0.9.3.

**Comment by Minopolis** [comment]
You're welcome.
