### ISSUE TITLE
glob dependency broken in 0.9.3

### ISSUE THREAD

**Issue by avaly** [macbre/analyze-css#83]
Version `0.9.3` introduced a bug where it includes the `glob` dependency in https://github.com/macbre/analyze-css/blob/86bf3648c05577dedfe4a5f16f0910669314fcf3/lib/preprocessors.js#L7, but `glob` is marked as a development dependency. Installing analyze-css in a project with `npm install --production` makes it unusable, since the `glob` is not installed.

**Comment by macbre** [comment]
Published as v0.9.4. Thanks for the report!
