### ISSUE TITLE
CSS parsing error handling

### ISSUE THREAD

**Issue by gmetais** [macbre/analyze-css#84]
https://github.com/reworkcss/css v2.2.0 is out. It now returns the AST with missing fields **and** a list of parsing errors when run in silent mode.

Analyze-css could do the same, I mean it could have a silent mode that doesn't break on error. It would then return:
- the metrics for all CSS rules that were be correctly parsed
- a new metric `parsingErrors`
- the error messages as offenders

**Comment by macbre** [comment]
Sure, I'd go even further and not fail when CSS parsing error take place. `analyze-css` is not a linting tool, so it should not fail when it's not necessary :)

A note to myself: https://github.com/reworkcss/css/pull/64
