### ISSUE TITLE
redundantChildNodesSelectors is missing tr-td and tr-th

### ISSUE THREAD

**Issue by gmetais** [macbre/analyze-css#88]
Hi @macbre!

Would it be possible to add detection for tr-td and th-td in the redundantChildNodesSelectors? It currently detects table-tr and table-th, but nothing for td...

**Comment by macbre** [comment]
Sure. Can you provide a few examples of such CSS selectors?

**Comment by gmetais** [comment]
Oops I juste realized I made a mistake. It's not th-td but tr-th.

```css
.foo tr td {}
.foo tr th {}
table.recommended tr td {}
table.tableborder tr.first td {}
table tr th.first {}
```

It would be even better if `table tr td` could be counted as one offender instead of 2: `table tr` and `tr td` if in the same expression. Same for `table tr th`.

**Comment by macbre** [comment]
Makes sense. Thanks for examples.
