### ISSUE TITLE
Update node-sass dependency version

### ISSUE THREAD

**Issue by ts-web** [macbre/analyze-css#89]
This package has `node-sass` listed as a dependency (version 1.1.2).

Version 1.1.2 of node-sass has a [pretty major bug](https://github.com/sass/node-sass/issues/497) that prevents some users from installing it. For me, it freezes my computer by consuming all my RAM. Therefore, I cannot install the `analyze-css` package since it requires `node-sass@1.1.2`

If the dependency version could be updated, that would probably fix the problem. `npm view node-sass` shows the latest 1.x version as `1.2.3`, and the very latest version as `3.0.0-alpha.0`. 

I don't know if this would break compatibility with the analyze-css package. Are there unit tests that would catch it? I'm new to the area of package management, so I don't know what the negative effects could be.

**Comment by macbre** [comment]
I wanted to update this dependency for a while, but was blocked by `node-sass` failing to compile on Debian  - https://github.com/sass/node-sass/issues/517

I'll try to update to the latest version from 2.x branch.

**Comment by macbre** [comment]
@ts-web, published to npm as v0.9.6
